#!/usr/bin/env python3

"""
    ******************************************************************************************
    Configuration file for WinkelstraatBot.
    Author: Ali Toori, Python Developer [Web-Automation Bot Developer | Web-Scraper Developer]
    Profiles:
        Upwork: https://www.upwork.com/freelancers/~011f08f1c849755c46
        Fiver: https://www.fiverr.com/alitoori
    ******************************************************************************************
"""

# The four categories and their subcategories with designers
HEREN_DICT = {
    'heren': ['/schoenen', '/jassen', '/kleding', '/accessoires', '/scooters'],
    'heren_schoenen': ['Floris-van-Bommel', 'HOGAN', 'Adidas', 'Santoni', 'A-cold-wall', 'AB-Lifestyle', 'Acne-Studios',
                       'Adidas-by-Raf-Simons', 'Alberto-Bellini', 'Alexander-McQueen', 'Alexander-Wang', 'Amiri',
                       'Android-Homme', 'Antony-Morato', 'ARKK-Copenhagen', 'Armani-Exchange', 'ASH-Italia', 'Asics',
                       'Atlantic-Stars', 'Australian', 'Axel-Arigato', 'Balenciaga', 'Balmain', 'Bikkembergs',
                       'Billionaire', 'Birkenstock', 'Bjorn-Borg', 'Blackstone', 'Bronx', 'Burberry', 'Calvin-Klein',
                       'Catwalk', 'Cavalli-Class', 'Celine', 'Cero-Nine', 'Champion', 'Church-s', 'Clarks',
                       'Clarks-Original', 'Closed', 'Colmar-Originals', 'Comme-des-Garcons', 'Common-Projects',
                       'Converse', 'Cortica', 'Cruyff', 'DATE', 'Dean-Rich', 'Diadora', 'Diadora-Heritage', 'Diesel',
                       'Dior', 'Dolce-Gabbana', 'Dr-Martens', 'dsquared2', 'Du00', 'EA7', 'Emporio-Armani',
                       'ETQ-Amsterdam', 'Fabienne-Chapot', 'Fendi', 'Fila', 'Filling-Pieces', 'Fred-Perry',
                       'G-star-Raw', 'Garment-Project', 'Ghoud', 'Gianvito-Rossi', 'Giorgio-Armani', 'Giuseppe-Zanotti',
                       'Givenchy', 'Golden-Goose', 'Gucci', 'Guess', 'Havaianas', 'Heron-Preston', 'Hi-Tec', 'Hinson',
                       'Hinson-Studios', 'Hugo', 'Hugo-Boss', 'Iceberg', 'In-Gold-We-Trust', 'Jeanrois', 'Jim-Rickey',
                       'Jimmy-Choo', 'John-Richmond', 'Karl-Lagerfeld', 'Kenzo', 'Lacoste', 'Lanvin', 'Loewe',
                       'Love-Moschino', 'Lyle-Scott', 'Mael-Studio', 'Magnanni', 'Maison-Kitsune', 'Maison-Margiela',
                       'Mallet', 'Marni', 'Mason-Garments', 'Massimo-Villa', 'MAURY', 'MCM', 'McQ-Alexander-McQueen',
                       'Mercer-Amsterdam', 'Michael-Kors', 'MISBHV', 'Moncler', 'Moreschi', 'Moschino', 'MSGM',
                       'My-Brand', 'N21', 'Neil-Barrett', 'New-Balance', 'Nike', 'Nubikk', 'OFF-THE-PITCH', 'OFF-WHITE',
                       'P448', 'Palm-Angels', 'Paul-Smith', 'Pharmacy-Club', 'Philipp-Plein', 'Philippe-Model', 'Prada',
                       'Premiata', 'Puma', 'Purewhite', 'Ralph-Lauren', 'Reebok', 'Rehab', 'Replay', 'Represent',
                       'Rick-Owens', 'Royal-Republiq', 'Saint-Laurent', 'Saucony', 'Scotch-Soda', 'Shabbies', 'SikSilk',
                       'Skechers', 'Stella-McCartney', 'Steve-Madden', 'Stokton', 'Superga', 'Sziano', 'Ted-Baker',
                       'Timberland', 'Tod-s', 'Tom-Ford', 'Tommy-Hilfiger', 'Trussardi-Jeans', 'UGG', 'Under-Armor',
                       'Valentino', 'Van-Bommel', 'Vans', 'Veja', 'Versace', 'Versace-Jeans', 'Woolrich', 'Y-3',
                       'Yves-Carter'],
    'heren_jassen': ['Parajumpers', 'Airforce', 'Peuterey', 'Herno', '1017-ALYX-9SM', 'A-cold-wall', 'AB-Lifestyle',
                     'Acne-Studios', 'Adidas', 'AH6', 'Alexander-McQueen', 'ALLDEY', 'Alpha-Industries', 'Amiri',
                     'Another-World-Clothing', 'Antony-Morato', 'Arc-teryx', 'Armani-Exchange', 'Aspesi', 'Australian',
                     'Balenciaga', 'Ballin-Amsterdam', 'Balmain', 'BALR', 'Be-edgy', 'Bikkembergs', 'Black-Bananas',
                     'Blauer', 'BomBoogie', 'Burberry', 'Calvin-Klein', 'Canada-Goose', 'Celesto', 'Celine',
                     'Circle-of-Trust', 'Closed', 'Colmar-Originals', 'Confirm', 'Conflict', 'CP-Company', 'Dean-Rich',
                     'Denham', 'Deus', 'Diesel', 'Dior', 'Dolce-Gabbana', 'Dondup', 'Drykorn', 'dsquared2', 'EA7',
                     'Elvine', 'Emporio-Armani', 'Equalite', 'Fendi', 'Fila', 'Filippa-K', 'Fred-Perry', 'G-star-Raw',
                     'GCDS', 'Genti', 'Gipsy', 'Givenchy', 'Golden-Goose', 'Goosecraft', 'Gucci', 'Guess', 'Helvetica',
                     'Heron-Preston', 'Hetrego', 'HOGAN', 'Hugo', 'Hugo-Boss', 'Iceberg', 'In-Gold-We-Trust',
                     'Jil-Sander', 'JorCustom', 'JOTT', 'Just-Junkies', 'Karl-Lagerfeld', 'Kenzo', 'Krakatau',
                     'Lacoste', 'Levi-s', 'Love-Moschino', 'Lyle-Scott', 'Ma-Strum', 'Maison-Margiela', 'Malelions',
                     'Marcelo-Burlon', 'Martine-Rose', 'Michael-Kors', 'Minimum', 'MISBHV', 'Moncler', 'Moose-Knuckles',
                     'Moschino', 'MSGM', 'Museum', 'My-Brand', 'Napapijri', 'Neil-Barrett', 'Nike', 'NN07',
                     'OFF-THE-PITCH', 'OFF-WHITE', 'Once-We-Were-Warriors', 'OSC', 'Palm-Angels', 'Patagonia',
                     'Paul-Smith', 'Peak-Performance', 'People-of-Shibuya', 'Philipp-Plein', 'Prada', 'Puma',
                     'Purewhite', 'Radical', 'Ralph-Lauren', 'Represent', 'Richesse', 'Rick-Owens', 'RRD',
                     'Saint-Laurent', 'Save-the-Duck', 'Scotch-Soda', 'SikSilk', 'Sixth-June', 'Stüssy', 'Sustain',
                     'The-GoodPeople', 'The-North-Face', 'Thom-Browne', 'Tommy-Hilfiger', 'Trussardi-Jeans',
                     'Under-Armor', 'Valentino', 'Versace', 'Versace-Jeans', 'Woolrich', 'Wrong-Friends',
                     'XPLCT-Studios', 'YCLO', 'Zumo', 'oLAF'],
    'heren_kleding': ['dsquared2', 'Ralph-Lauren', 'Purewhite', 'Kenzo', '1017-ALYX-9SM', '24UOMO', '7-For-All-Mankind',
                      'A-cold-wall', 'APC', 'AB-Lifestyle', 'Acne-Studios', 'Adidas', 'Adidas-by-Raf-Simons', 'AH6',
                      'Airforce', 'AK', 'Alberto-Bellini', 'Alexander-McQueen', 'Alexander-Wang', 'Alife®', 'ALLDEY',
                      'Alpha-Industries', 'Amiri', 'Android-Homme', 'Another-World-Clothing', 'Antony-Morato',
                      'Arc-teryx', 'ARKK-Copenhagen', 'Armani-Exchange', 'Armani-Jeans', 'ASH-Italia', 'Asics',
                      'Aspesi', 'Atlantic-Stars', 'Australian', 'Avior', 'Axel-Arigato', 'Balenciaga',
                      'Ballin-Amsterdam', 'Balmain', 'BALR', 'Bargain', 'Be-edgy', 'Believe-that', 'Bikkembergs',
                      'Billionaire', 'Billionaire-Boys-Club', 'Birkenstock', 'Bjorn-Borg', 'Black-Bananas',
                      'Blackstone', 'Blauer', 'BomBoogie', 'Boragio', 'Bronx', 'BTQ24', 'Buddha-to-Buddha', 'Burberry',
                      'Buscemi', 'Butcher-of-Blue', 'By-Risque', 'Calvin-Klein', 'Calvin-Klein-205W39NYC',
                      'Canada-Goose', 'Capslab', 'Carhartt', 'Carlo-Colucci', 'Casablanca', 'Catwalk', 'Cavalli-Class',
                      'Ceasarss', 'Celesto', 'Celine', 'Cero-Nine', 'Champion', 'Christian-Louboutin', 'Church-s',
                      'Circle-of-Trust', 'Clan-de-Banlieue', 'Clarks', 'Clarks-Original', 'Closed', 'Colmar-Originals',
                      'Comme-des-Garcons', 'Common-Projects', 'Confirm', 'Conflict', 'Converse', 'Corneliani',
                      'Cortica', 'CP-Company', 'Cruyff', 'Daily-Paper', 'Daniele-Fiesoli', 'DATE', 'Dean-Rich',
                      'Denham', 'Deus', 'Diadora', 'Diadora-Heritage', 'Diesel', 'DIMORAL', 'Dior', 'Dita',
                      'Dolce-Gabbana', 'Dondup', 'Dr-Martens', 'Drôle-de-Monsieur', 'Drykorn', 'Du00', 'EA7', 'Elvine',
                      'Emporio-Armani', 'Equalite', 'ETQ-Amsterdam', 'Evisu', 'Fabienne-Chapot', 'Farlo-PalU',
                      'Federal-Jeans', 'Fendi', 'FIGHTR', 'Fila', 'Filippa-K', 'Filling-Pieces', 'Floris-van-Bommel',
                      'Fossil', 'Frankie-Morello', 'Fred-Perry', 'Future-Icon', 'G-star-Raw', 'Gabba',
                      'Garment-Project', 'GCDS', 'Genti', 'Gentiluomo', 'Ghoud', 'Gianvito-Rossi', 'Gigi-Vitale',
                      'Giorgio-Armani', 'Gipsy', 'Giuseppe-Zanotti', 'Given', 'Givenchy', 'Goldbergh', 'Golden-Goose',
                      'Goorin-Brothers', 'Goosecraft', 'GREG-NOISE', 'Gucci', 'Guess', 'Havaianas', 'Helvetica',
                      'Herno', 'Heron-Preston', 'Hetrego', 'Hi-Tec', 'Hinson', 'Hinson-Studios', 'HOGAN', 'Hugo',
                      'Hugo-Boss', 'Ibana', 'Iceberg', 'Iceplay', 'In-Gold-We-Trust', 'Isabel-Marant', 'J-Brand',
                      'Jacob-Cohen', 'Jeanrois', 'Jil-Sander', 'Jim-Rickey', 'Jimmy-Choo', 'John-Richmond', 'JorCustom',
                      'Jorik', 'JOTT', 'Just-Cavalli', 'Just-Junkies', 'Kappa', 'Karl-Lagerfeld', 'Kent-Curwen',
                      'Kings-Will-Dream', 'Krakatau', 'Kultivate', 'Lacoste', 'Lanvin', 'Levi-s', 'LEYON', 'Limitato',
                      'Liu-Jo', 'Loewe', 'Lorenzoni', 'Love-Moschino', 'Lyle-Scott', 'MaStrum', 'Mael-Studio',
                      'Magnanni', 'Maison-Kitsune', 'Maison-Margiela', 'Malelions', 'Mallet', 'Marc-Jacobs',
                      'Marcelo-Burlon', 'Marni', 'Martine-Rose', 'Mason-Garments', 'Mason-s', 'Massimo-Villa', 'MAURY',
                      'MCM', 'McQ-Alexander-McQueen', 'Mercer-Amsterdam', 'MESMO-since-day-one', 'Michael-Kors',
                      'Minimum', 'MISBHV', 'Missoni', 'MLLNR', 'Moncler', 'Moose-Knuckles', 'Moreschi', 'Morse-Code',
                      'Moschino', 'MSGM', 'Museum', 'My-Brand', 'N21', 'Napapijri', 'Neil-Barrett',
                      'New-Amsterdam-Surf-Association', 'New-Balance', 'New-Era', 'NEWAMS', 'Nike',
                      'Nine-in-the-morning', 'Ninetyfour', 'NN07', 'Nubikk', 'Nudie-Jeans', 'Oakley', 'OFF-THE-PITCH',
                      'OFF-WHITE', 'Once-We-Were-Warriors', 'OSC', 'P448', 'Palm-Angels', 'Parajumpers', 'Patagonia',
                      'Patrizia-Pepe', 'Paul-Shark', 'Paul-Smith', 'Peak-Performance', 'People-of-Shibuya', 'Peuterey',
                      'Pharmacy-Club', 'Philipp-Plein', 'Philippe-Model', 'Philosophy', 'Plain', 'Pleasures', 'Prada',
                      'Premiata', 'Profuomo', 'PRPS', 'Puma', 'Pyrex', 'Quotrell', 'Radical', 'Raf-Simons', 'Reebok',
                      'Rehab', 'Reinders', 'Replay', 'Represent', 'Reprimand', 'Rhude', 'Richesse', 'Rick-Owens',
                      'ROKA-Original', 'Royal-Republiq', 'RRD', 'RTA', 'Saint-Laurent', 'Samsoe-Samsoe', 'Santoni',
                      'Saucony', 'Save-the-Duck', 'Scotch-Soda', 'Shabbies', 'SikSilk', 'Sixth-June', 'Skechers',
                      'splinter', 'Sprayground', 'Statementmask', 'Stella-McCartney', 'Steve-Madden', 'Stokton',
                      'Stüssy', 'sundek', 'Superga', 'Sustain', 'Sziano', 'Tagliatore', 'Ted-Baker', 'The-GoodPeople',
                      'The-North-Face', 'Thom-Browne', 'Throwback', 'Tigha', 'Timberland', 'Tod-s', 'Tom-Ford',
                      'Tommy-Hilfiger', 'Trussardi-Jeans', 'TW-Steel', 'UGG', 'Under-Armor', 'Unknown-Army',
                      'Valentino', 'VALENTINO-BY-MARIO-VALENTINO', 'Van-Bommel', 'Vans', 'Veja', 'Versace',
                      'Versace-Jeans', 'Versus', 'Vespa', 'Winkelstraat-nl', 'Woolrich', 'Wrong-Friends',
                      'XPLCT-Studios', 'Y-3', 'YCLO', 'Yves-Carter', 'Zumo', 'oLAF'],
    'heren_scooters': ['Vespa'],
    'heren_accessoires': ['dsquared2', 'Alexander-McQueen', 'Kenzo', 'OFF-WHITE', '1017-ALYX-9SM', 'A-cold-wall', 'APC',
                          'AB-Lifestyle', 'Acne-Studios', 'Adidas', 'Airforce', 'Alberto-Bellini', 'Alexander-Wang',
                          'ALLDEY', 'Antony-Morato', 'Balenciaga', 'Balmain', 'BALR', 'Black-Bananas', 'Boragio',
                          'BTQ24', 'Burberry', 'Buscemi', 'Calvin-Klein', 'Capslab', 'Carlo-Colucci', 'Celesto',
                          'Celine', 'Christian-Louboutin', 'Church-s', 'CP-Company', 'Dean-Rich', 'Deus', 'Diesel',
                          'Dior', 'Dita', 'Dolce-Gabbana', 'Dondup', 'Dr-Martens', 'Drôle-de-Monsieur',
                          'Emporio-Armani', 'Equalite', 'Fendi', 'Fila', 'Floris-van-Bommel', 'Fossil', 'Future-Icon',
                          'Givenchy', 'Goldbergh', 'Golden-Goose', 'Goorin-Brothers', 'Gucci', 'Heron-Preston', 'HOGAN',
                          'Hugo-Boss', 'Iceberg', 'In-Gold-We-Trust', 'Jacob-Cohen', 'Jimmy-Choo', 'Jorik', 'Lacoste',
                          'Lanvin', 'Liu-Jo', 'Lyle-Scott', 'Mael-Studio', 'Magnanni', 'Maison-Kitsune',
                          'Maison-Margiela', 'Malelions', 'Marcelo-Burlon', 'Marni', 'McQ-Alexander-McQueen',
                          'Michael-Kors', 'MISBHV', 'Moncler', 'Moose-Knuckles', 'Moreschi', 'Moschino', 'MSGM',
                          'My-Brand', 'Napapijri', 'Neil-Barrett', 'OFF-THE-PITCH', 'Once-We-Were-Warriors',
                          'Palm-Angels', 'Parajumpers', 'Patagonia', 'Paul-Smith', 'Peuterey', 'Pharmacy-Club',
                          'Philipp-Plein', 'Philosophy', 'Prada', 'Quotrell', 'Ralph-Lauren', 'Rick-Owens',
                          'ROKA-Original', 'Royal-Republiq', 'Saint-Laurent', 'Santoni', 'Sprayground', 'Statementmask',
                          'Sustain', 'The-GoodPeople', 'The-North-Face', 'Thom-Browne', 'Tom-Ford', 'Tommy-Hilfiger',
                          'TW-Steel', 'Unknown-Army', 'Valentino', 'VALENTINO-BY-MARIO-VALENTINO', 'Versace',
                          'Versace-Jeans', 'Woolrich', 'Wrong-Friends', 'XPLCT-Studios', 'Y-3', 'YCLO'],}

DAMES_DICT = {
    'dames': ['/schoenen', '/jassen', '/tassen', '/accessoires', '/vintage', '/kleding'],
    'dames_schoenen': ['UGG', 'Michael-Kors', 'HOGAN', 'MAURY', 'Aaiko', 'Acne-Studios', 'Adidas',
                       'Adidas-by-Raf-Simons', 'Adidas-by-Stella-McCartney', 'Alaia', 'Alberta-Ferretti',
                       'Alberto-Bellini', 'Alberto-Gozzi', 'Alexander-McQueen', 'Alexander-Smith', 'Alexander-Wang',
                       'Alexandre-Birman', 'Alexandre-Vauthier', 'Android', 'Anine-Bing', 'Aquazzura',
                       'ARKK-Copenhagen', 'Armani-Jeans', 'ASH-Italia', 'Asics', 'Atlantic-Stars',
                       'Attilio-Giusti-Leombruni', 'Axel-Arigato', 'Balenciaga', 'Bally', 'Balmain', 'Bibi-Lou',
                       'Birkenstock', 'Bjorn-Borg', 'Blackstone', 'Bottega-Veneta', 'Bronx', 'Burberry', 'Calvin-Klein',
                       'Casadei', 'Catwalk', 'Celine', 'Cero-Nine', 'Chiara-Ferragni', 'Chloe', 'Christian-Louboutin',
                       'Church-s', 'Clarks', 'Clic', 'CLJD', 'Colmar-Originals', 'Comme-des-Garcons', 'Common-Projects',
                       'Converse', 'Copenhagen', 'Cruyff', 'DATE', 'Diadora', 'Diadora-Heritage', 'Diesel', 'Dior',
                       'DKNY', 'Dolce-Gabbana', 'Dondup', 'Dr-Martens', 'Dries-van-Noten', 'dsquared2', 'EA7',
                       'Elenia-Lachi', 'Elisabetta-Franchi', 'Ellesse', 'Emporio-Armani', 'Essential', 'ETQ-Amsterdam',
                       'Fabienne-Chapot', 'Fendi', 'Fiamme', 'Fifth-House', 'Fila', 'Floris-van-Bommel',
                       'Francesco-Russo', 'Fred-de-la-Bretoniere', 'Frida', 'G-star-Raw', 'GCDS', 'Ghoud',
                       'Gianvito-Rossi', 'Giorgio-Armani', 'Giuseppe-Zanotti', 'Givenchy', 'Golden-Goose', 'Gucci',
                       'Guess', 'Guglielmo-Rotta', 'Hi-Tec', 'HIP', 'Isabel-Marant', 'Janet-Janet', 'Jil-Sander',
                       'Jimmy-Choo', 'Jo-Ghost', 'Josh-V', 'Kappa', 'Karl-Lagerfeld', 'Kat-Maconie', 'Kendall-Kylie',
                       'Kennel-Schmenger', 'Kenzo', 'Lacoste', 'Lanvin', 'Liu-Jo', 'Lola-Cruz', 'Love-Moschino',
                       'Lyle-Scott', 'Maison-Kitsune', 'Maison-Margiela', 'Mallet', 'Marc-Cain', 'Marc-Jacobs',
                       'March-23', 'Marni', 'Mason-Garments', 'McQ-Alexander-McQueen', 'Mercer-Amsterdam', 'Miu-Miu',
                       'MM6-Maison-Margiela', 'Moncler', 'Moschino', 'MSGM', 'N21', 'Nero-Giardini', 'New-Balance',
                       'Nik-Nik', 'Nike', 'Nikkie', 'Nubikk', 'OFF-WHITE', 'P448', 'Paris-Punk', 'Patrizia-Pepe',
                       'Paul-Smith', 'Pedro-Miralles', 'Pertini', 'Peter-Kaiser', 'Philipp-Plein', 'Philippe-Model',
                       'Philosophy', 'Philou', 'Pinko', 'Poelman', 'Prada', 'Premiata', 'Proenza-Schouler', 'Puma',
                       'Save-Valentino', 'Reebok', 'Reinders', 'Rick-Owens', 'Roberto-D-Angelo', 'Rotta',
                       'Royal-Republiq', 'Saint-Laurent', 'Santoni', 'Saucony', 'Scotch-Soda', 'Sendra', 'Sergio-Rossi',
                       'Shabbies', 'Skechers', 'Stella-McCartney', 'Steve-Madden', 'Stokton', 'Stuart-Weitzman',
                       'Superga', 'Super-trash', 'SVNTY', 'TANGO', 'Ted-Baker', 'Timberland', 'Tod-s', 'Tommy-Hilfiger',
                       'Toral', 'Tory-Burch', 'Trussardi-Jeans', 'Twin-set', 'Under-Armor', 'Unisa', 'Valentino',
                       'Vans', 'Veja', 'Versace', 'Versace-Jeans', 'Vetements', 'Via-Vai', 'Voile-Blanche', 'Wandler',
                       'What-For', 'Woolrich', 'Y-3', 'Yeezy', 'Zadig-et-Voltaire'],
    'dames_jassen': ['Parajumpers', 'Herno', 'Airforce', 'Burberry', 'Acne-Studios', 'Adidas', 'Alexander-McQueen',
                     'Alexandre-Vauthier', 'ALIX', 'Alpha-Industries', 'Arma-Leder', 'Armani-Exchange', 'Aspesi',
                     'Balenciaga', 'Balmain', 'Baum-und-Pferdgarten', 'Blauer', 'Calvin-Klein',
                     'Calvin-Klein-205W39NYC', 'Canada-Goose', 'Canadian-Classics', 'Chiara-Ferragni',
                     'Circle-of-Trust', 'Closed', 'Colmar-Originals', 'Dante-6', 'Dean-Rich', 'Desa', 'DKNY',
                     'Dolce-Gabbana', 'Dondup', 'Dries-van-Noten', 'Drykorn', 'dsquared2', 'EA7', 'Elisabetta-Franchi',
                     'Elvine', 'Emporio-Armani', 'Fendi', 'Fila', 'Gestuz', 'Giacomo', 'Giorgio-Armani', 'Gipsy',
                     'Givenchy', 'Goldbergh', 'Golden-Goose', 'Goosecraft', 'Gucci', 'Guess', 'Helvetica',
                     'Heron-Preston', 'High', 'Hugo-Boss', 'Ibana', 'Iceplay', 'Iro', 'Isabel-Marant', 'Jacky-Luxury',
                     'Jil-Sander', 'Josh-V', 'JOTT', 'Karl-Lagerfeld', 'Kenzo', 'Kocca', 'Krakatau', 'LA-Sisters',
                     'Levi-s', 'Liu-Jo', 'Love-Moschino', 'Ma-Strum', 'Maison-Margiela', 'Majestic', 'Marni',
                     'Max-Mara', 'Michael-Kors', 'Missoni', 'Miu-Miu', 'Moncler', 'Moose-Knuckles', 'Moschino',
                     'Moscow', 'MSGM', 'NA-KD', 'Napapijri', 'Nikkie', 'OFF-WHITE', 'OSC', 'Patrizia-Pepe', 'Peuterey',
                     'Philipp-Plein', 'Philosophy', 'Pinko', 'Prada', 'Ralph-Lauren', 'Save-Valentino', 'Reinders',
                     'Replay', 'Reset', 'Rick-Owens', 'RRD', 'Sacai', 'Saint-Laurent', 'Save-the-Duck', 'Scotch-Soda',
                     'Set', 'Stand', 'Stella-McCartney', 'Summum', 'Tagliatore', 'Tommy-Hilfiger', 'Twin-set',
                     'Twisted-babydoll', 'Under-Armor', 'Valentino', 'Woolrich'],
    'dames_tassen': ['Michael-Kors', 'Guess', 'Love-Moschino', 'VALENTINO-BY-MARIO-VALENTINO', 'Acne-Studios', 'Adidas',
                     'Alberta-Ferretti', 'Alberto-Bellini', 'Alexander-McQueen', 'ALIX', 'Anine-Bing', 'Balenciaga',
                     'Bally', 'Balmain', 'Burberry', 'By-Malene-Birger', 'Calvin-Klein', 'Casadei', 'Catwalk',
                     'Cavalli-Class', 'Celine', 'Chiara-Ferragni', 'Chloe', 'Christian-Louboutin', 'Coach',
                     'Coccinelle', 'Dance-Spring', 'Desa', 'Diane-Von-Furstenberg', 'DKNY', 'Dolce-Gabbana',
                     'dsquared2', 'Elisabetta-Franchi', 'Emporio-Armani', 'Essential', 'Fabienne-Chapot', 'Fendi',
                     'Fila', 'Furla', 'Gianni-Chiarini', 'Giorgio-Armani', 'Giuseppe-Zanotti', 'Givenchy',
                     'Golden-Goose', 'Gucci', 'Heron-Preston', 'HOGAN', 'Hvisk', 'Iceplay', 'Isabel-Marant',
                     'Jil-Sander', 'Jimmy-Choo', 'Karl-Lagerfeld', 'Kenzo', 'Lacoste', 'Lanvin', 'Liu-Jo', 'Loewe',
                     'Maison-Margiela', 'Marc-Jacobs', 'Marcelo-Burlon', 'Marni', 'McQ-Alexander-McQueen',
                     'MM6-Maison-Margiela', 'Moncler', 'Moschino', 'MSGM', 'Nikkie', 'OFF-WHITE', 'Patrizia-Pepe',
                     'Philipp-Plein', 'Pinko', 'Prada', 'Ralph-Lauren', 'Reinders', 'Replay', 'Rick-Owens',
                     'Roberto-D-Angelo', 'Saint-Laurent', 'Sprayground', 'Stella-McCartney', 'Ted-Baker', 'Tod-s',
                     'Tommy-Hilfiger', 'Tory-Burch', 'Twin-set', 'Unisa', 'Valentino', 'Versace', 'Versace-Jeans',
                     'Wandler', 'Woolrich', 'Y-3'],
    'dames_accessoires': ['Michael-Kors', 'Guess', 'Gucci', 'Buddha-to-Buddha', '10-Days', 'A-P-C', 'Alberta-Ferretti',
                          'Alexander-McQueen', 'ALIX', 'Balenciaga', 'Balmain', 'BTQ24', 'Burberry', 'By-Malene-Birger',
                          'Calvin-Klein', 'Cavalli-Class', 'Celine', 'Chiara-Ferragni', 'Chloe', 'Christian-Louboutin',
                          'Church-s', 'Coach', 'Dior', 'Dolce-Gabbana', 'Dries-van-Noten', 'dsquared2',
                          'Elisabetta-Franchi', 'Emporio-Armani', 'Fendi', 'Floris-van-Bommel', 'For-Art-s-Sake',
                          'Fossil', 'Freebird', 'Furla', 'GCDS', 'Gianni-Chiarini', 'Giuseppe-Zanotti', 'Givenchy',
                          'Heron-Preston', 'Hugo-Boss', 'Isabel-Marant', 'Jimmy-Choo', 'Jorik', 'Karl-Lagerfeld',
                          'Kenzo', 'Liu-Jo', 'Loewe', 'Love-Moschino', 'Marc-Jacobs', 'Marni', 'Moncler', 'Moschino',
                          'MSGM', 'Nikkie', 'OFF-THE-PITCH', 'OFF-WHITE', 'Paul-Smith', 'Philosophy', 'Pinko', 'Prada',
                          'Proenza-Schouler', 'Purewhite', 'Ralph-Lauren', 'Rick-Owens', 'Saint-Laurent',
                          'Statementmask', 'Ted-Baker', 'Tod-s', 'Tom-Ford', 'Tommy-Hilfiger', 'Tory-Burch', 'UGG',
                          'Valentino', 'VALENTINO-BY-MARIO-VALENTINO', 'Versace', 'Versace-Jeans', 'VICTORIA-BECKHAM',
                          'Vivienne-Westwood'],
    'dames_vintage': ['Chanel', 'Louis-Vuitton', 'Gucci', 'Saint-Laurent', 'Dior', 'Hermes'],
    'dames_kleding': ['Guess', 'Liu-Jo', 'UGG', '10-Days', '304', '7-For-All-Mankind', 'APC', 'Aaiko', 'Acne-Studios',
                      'Adidas', 'Adidas-by-Raf-Simons', 'Adidas-by-Stella-McCartney', 'AH6', 'Airforce', 'Alaia',
                      'Alberta-Ferretti', 'Alberto-Bellini', 'Alberto-Gozzi', 'Alexander-McQueen', 'Alexander-Smith',
                      'Alexander-Wang', 'Alexandre-Birman', 'Alexandre-Vauthier', 'ALIX', 'ALLDEY', 'Alpha-Industries',
                      'Alyx', 'AMI-Paris', 'Android', 'Anine-Bing', 'Aquazzura', 'ARKK-Copenhagen', 'Arma-Leder',
                      'Armani-Exchange', 'Armani-Jeans', 'ASH-Italia', 'Asics', 'Aspesi', 'Atlantic-Stars',
                      'Attilio-Giusti-Leombruni', 'Australian', 'Axel-Arigato', 'Ba-sh', 'Balenciaga', 'Bally',
                      'Balmain', 'Baum-und-Pferdgarten', 'Bella-Dahl', 'Bella-Freud', 'Bianco', 'Bibi-Lou',
                      'Birkenstock', 'Bjorn-Borg', 'Blackstone', 'Blauer', 'Bottega-Veneta', 'Boutique-Moschino',
                      'Bronx', 'BTQ24', 'Buddha-to-Buddha', 'Burberry', 'Butcher-of-Blue', 'By-Malene-Birger',
                      'Calvin-Klein', 'Calvin-Klein-205W39NYC', 'Cambio', 'Canada-Goose', 'Canadian-Classics',
                      'Casadei', 'Catwalk', 'Catwalk-Junkie', 'Cavalli-Class', 'Celine', 'Cero-Nine', 'Chanel',
                      'Chiara-Ferragni', 'Chloe', 'Christian-Louboutin', 'Church-s', 'Circle-of-Trust', 'Clarks',
                      'Clic', 'CLJD', 'Closed', 'Coach', 'Coccinelle', 'Colmar-Originals', 'Comme-des-Garcons',
                      'Common-Projects', 'Converse', 'Copenhagen', 'Cruyff', 'Dance-Spring', 'Dante-6', 'DATE',
                      'Dean-Rich', 'Denham', 'Desa', 'Diadora', 'Diadora-Heritage', 'Diane-Von-Furstenberg', 'Diesel',
                      'Dior', 'DKNY', 'Dolce-Gabbana', 'Dondup', 'Dr-Martens', 'Dries-van-Noten', 'Drykorn',
                      'dsquared2', 'EA7', 'Elenia-Lachi', 'Elisabetta-Franchi', 'Ellesse', 'Elvine', 'Emporio-Armani',
                      'Equipment', 'Essential', 'ETQ-Amsterdam', 'Evisu', 'Expresso', 'Fabiana-Filippi',
                      'Fabienne-Chapot', 'Farlo-PalU', 'Fendi', 'Fiamme', 'Fifth-House', 'Fila', 'Filippa-K',
                      'Fiorucci', 'Floris-van-Bommel', 'For-Art-s-Sake', 'Fossil', 'Francesco-Russo',
                      'Fred-de-la-Bretoniere', 'Freebird', 'Frida', 'Furla', 'Future-Icon', 'G-star-Raw', 'Ganni',
                      'GCDS', 'Gestuz', 'Ghoud', 'Giacomo', 'Gianni-Chiarini', 'Gianvito-Rossi', 'Giorgio-Armani',
                      'Gipsy', 'Giuseppe-Zanotti', 'Given', 'Givenchy', 'Glamorous', 'Goldbergh', 'Golden-Goose',
                      'Goosecraft', 'GREG-NOISE', 'Gucci', 'Guglielmo-Rotta', 'Helmut-Lang', 'Helvetica', 'Hermes',
                      'Herno', 'Heron-Preston', 'Hi-Tec', 'High', 'HIP', 'HOGAN', 'Hugo-Boss', 'Hvisk', 'Ibana',
                      'Iceberg', 'Iceplay', 'Iro', 'Isabel-Marant', 'J-Brand', 'Jacky-Luxury', 'Jacob-Cohen',
                      'Janet-Janet', 'Japan-TKY', 'Jil-Sander', 'Jimmy-Choo', 'Jo-Ghost', 'Jorik', 'Joseph', 'Josh-V',
                      'JOTT', 'Just-Cavalli', 'Just-Junkies', 'Kappa', 'Karl-Lagerfeld', 'Kat-Maconie', 'Kendall-Kylie',
                      'Kennel-Schmenger', 'Kenzo', 'Kocca', 'Krakatau', 'LA-Sisters', 'Lacoste', 'Lanvin', 'Levi-s',
                      'Loewe', 'Lois', 'Lola-Cruz', 'Louis-Vuitton', 'Love-Moschino', 'Lyle-Scott', 'Ma-Strum',
                      'Maison-Kitsune', 'Maison-Margiela', 'Maison-Scotch', 'Majestic', 'Mallet', 'Marc-Cain',
                      'Marc-Jacobs', 'Marcelo-Burlon', 'March-23', 'Maria-Tailor', 'Marni', 'Mason-Garments', 'MAURY',
                      'Max-Mara', 'MbyM', 'McQ-Alexander-McQueen', 'Mercer-Amsterdam', 'MESMO-since-day-one',
                      'WITH-Jeans', 'Milla-Amsterdam', 'Minimum', 'Miss-June', 'Missoni', 'Miu-Miu',
                      'MM6-Maison-Margiela', 'Modstrom', 'Moncler', 'Moose-Knuckles', 'Moost-Wanted', 'Mos-Mosh',
                      'Moschino', 'Moscow', 'Moss-Copenhagen', 'MSGM', 'My-Brand', 'N21', 'NA-KD', 'Napapijri',
                      'Nero-Giardini', 'New-Balance', 'Nik-Nik', 'Nike', 'Nikkie', 'Nubikk', 'OFF-THE-PITCH',
                      'OFF-WHITE', 'OSC', 'P448', 'Palm-Angels', 'Parajumpers', 'Paris-Punk', 'Patrizia-Pepe',
                      'Paul-Smith', 'Pedro-Miralles', 'Penn-Ink', 'Pertini', 'Peter-Kaiser', 'Peuterey',
                      'Philipp-Plein', 'Philippe-Model', 'Philosophy', 'Philou', 'Pinko', 'Poelman', 'Prada',
                      'Premiata', 'Proenza-Schouler', 'Puma', 'Purewhite', 'Radical', 'Ragyard', 'Ralph-Lauren',
                      'Save-Valentino', 'Reebok', 'Reinders', 'Repeat', 'Replay', 'Represent', 'Reset', 'Richesse',
                      'Rick-Owens', 'rinascimento', 'Robert-Friedman', 'Roberto-D-Angelo', 'Rotta', 'Rough-Studios',
                      'Royal-Republiq', 'Royal-Temptation', 'RRD', 'Sacai', 'Saint-Laurent', 'Samsoe-Samsoe', 'Santoni',
                      'Saucony', 'Save-the-Duck', 'Scotch-Soda', 'Second-Female', 'Self-Portrait', 'Sendra',
                      'Sergio-Rossi', 'Set', 'Shabbies', 'She-Is-Us', 'SikSilk', 'Silvian-Heach', 'Sixth-June',
                      'Skechers', 'Sprayground', 'Stand', 'Statementmask', 'Stella-McCartney', 'Steve-Madden',
                      'Stine-Goya', 'Stokton', 'Stuart-Weitzman', 'Studio-Anneloes', 'Stüssy', 'Summum', 'Superga',
                      'Super-trash', 'SVNTY', 'Tagliatore', 'TANGO', 'Ted-Baker', 'Timberland', 'Tod-s', 'Tom-Ford',
                      'Tommy-Hilfiger', 'Toral', 'Tory-Burch', 'Trussardi-Jeans', 'Twin-set', 'Twisted-babydoll',
                      'Under-Armor', 'Unisa', 'Valentino', 'VALENTINO-BY-MARIO-VALENTINO', 'Vans', 'Veja', 'Versace',
                      'Versace-Jeans', 'Versus', 'Vetements', 'Via-Vai', 'VICTORIA-BECKHAM', 'Vince',
                      'Vivienne-Westwood', 'Voile-Blanche', 'Wanderlust', 'Wandler', 'What-For', 'Winkelstraat-nl',
                      'Woolrich', 'XPLCT-Studios', 'Y-3', 'Yaya', 'yeezlouise', 'Yeezy', 'Zadig-et-Voltaire',
                      'Zoe-Karssen'],}

KINDEREN_DICT = {
    'kinderen': ['/jongens', '/meisjes', '/babys'],
    'kinderen_jongens': ['dsquared2', 'Moncler', 'Gucci', 'Antony-Morato', 'AB-Lifestyle', 'Adidas', 'Airforce',
                         'Alexander-McQueen', 'ARKK-Copenhagen', 'Armani-Baby', 'Armani-Junior', 'Asics', 'Balenciaga',
                         'Ballin-Amsterdam', 'Balmain', 'Bikkembergs', 'Bjorn-Borg', 'Black-Bananas', 'Blackstone',
                         'Burberry', 'Calvin-Klein', 'Canadiens', 'Cero-Nine', 'Champion', 'Chloe', 'Converse',
                         'CP-Company', 'Diadora', 'Diesel', 'Dolce-Gabbana', 'Dr-Martens', 'EA7', 'Emporio-Armani',
                         'Fendi', 'Fila', 'Future-Icon', 'GCDS', 'Givenchy', 'Golden-Goose', 'Guess', 'Herno', 'HOGAN',
                         'Hugo-Boss', 'Iceberg', 'In-Gold-We-Trust', 'Kappa', 'Karl-Lagerfeld', 'Kenzo', 'Lacoste',
                         'Levi-s', 'Lyle-Scott', 'Malelions', 'Mallet', 'Marc-Jacobs', 'Marcelo-Burlon', 'Marni',
                         'Mason-Garments', 'Monnalisa', 'Moose-Knuckles', 'Moschino', 'MSGM', 'My-Brand', 'Napapijri',
                         'Neil-Barrett', 'New-Balance', 'Nik-Nik', 'Nike', 'Parajumpers', 'Patrizia-Pepe', 'Peuterey',
                         'Philipp-Plein', 'Philippe-Model', 'Puma', 'Ralph-Lauren', 'Reebok', 'Reinders', 'Replay',
                         'Saucony', 'Scotch-Soda', 'Stella-McCartney', 'Stone-Island-Junior', 'Superga',
                         'Tartine-et-Chocolat', 'Timberland', 'Tod-s', 'Tommy-Hilfiger', 'UGG', 'Under-Armour', 'Vans',
                         'Versace', 'Woolrich'],
    'kinderen_meisjes': ['Monnalisa', 'Kenzo', 'dsquared2', 'Liu-Jo', 'Adidas', 'Airforce', 'Alberta-Ferretti',
                         'Alexander-McQueen', 'Armani-Junior', 'Balenciaga', 'Ballin-Amsterdam', 'Balmain', 'Blumarine',
                         'Burberry', 'Calvin-Klein', 'Canadiens', 'Chloe', 'Clarks', 'Clic', 'Converse', 'Diadora',
                         'Diesel', 'Dolce-Gabbana', 'Dr-Martens', 'Elisabetta-Franchi', 'Emporio-Armani',
                         'Fabienne-Chapot', 'Fendi', 'Fila', 'Future-Icon', 'Givenchy', 'Golden-Goose', 'Gucci',
                         'Guess', 'Guess-by-Marciano', 'HOGAN', 'Hugo-Boss', 'Iceberg', 'Jacky-Luxury', 'Kappa',
                         'Karl-Lagerfeld', 'Lacoste', 'Levi-s', 'Malelions', 'Marc-Jacobs', 'Michael-Kors', 'Moncler',
                         'Moose-Knuckles', 'Moschino', 'MSGM', 'My-Brand', 'Napapijri', 'Nero-Giardini', 'New-Balance',
                         'Nik-Nik', 'Nike', 'Nikkie', 'Parajumpers', 'Patrizia-Pepe', 'Philipp-Plein', 'Philippe-Model',
                         'Philosophy', 'Pinko', 'Puma', 'Ralph-Lauren', 'Reinders', 'Replay', 'Saucony',
                         'Stella-McCartney', 'Steve-Madden', 'Tartine-et-Chocolat', 'Timberland', 'Tod-s',
                         'Tommy-Hilfiger', 'Twin-set', 'Twistedbabydoll', 'UGG', 'Versace', 'Woolrich'],
    'kinderen_babys': ['MSGM', 'Givenchy', 'Balmain', 'Kenzo', 'Diesel', 'Dolce-Gabbana', 'dsquared2', 'Emporio-Armani',
                       'Fendi', 'Hugo-Boss', 'Marcelo-Burlon', 'Moncler', 'Monnalisa', 'Moschino', 'My-Brand',
                       'Philipp-Plein', 'Ralph-Lauren', 'Tartine-et-Chocolat'],}
DESIGNERS_DICT = {
    'designer_all': ['10-DAYS', '1017-ALYX-9SM', '24UOMO', '304', '7-FOR-ALL-MANKIND', 'A-COLD-WALL', 'APC', 'AAIKO', 'AB-LIFESTYLE', 'ACNE-STUDIOS', 'ADIDAS', 'ADIDAS-BY-RAF-SIMONS', 'ADIDAS-BY-STELLA-MCCARTNEY', 'AH6', 'AIRFORCE', 'AK', 'ALAIA', 'ALBERTA-FERRETTI', 'ALBERTO-BELLINI', 'ALBERTO-GOZZI', 'ALEXANDER-MCQUEEN', 'ALEXANDER-SMITH', 'ALEXANDER-WANG', 'ALEXANDRE-BIRMAN', 'ALEXANDRE-VAUTHIER', 'ALIFE®', 'ALIX', 'ALLDEY', 'ALPHA-INDUSTRIES', 'ALYX', 'AMI-PARIS', 'AMIRI', 'ANDROID', 'ANDROID-HOMME', 'ANINE-BING', 'ANOTHER-WORLD-CLOTHING', 'ANTONY-MORATO', 'AQUAZZURA', 'ARC-TERYX', 'ARKK-COPENHAGEN', 'ARMA-LEDER', 'ARMANI-BABY', 'ARMANI-EXCHANGE', 'ARMANI-JEANS', 'ARMANI-JUNIOR', 'ASH-ITALIA', 'ASICS', 'ASPESI', 'ATLANTIC-STARS', 'ATTILIO-GIUSTI-LEOMBRUNI', 'AUSTRALIAN', 'AVIOR', 'AXEL-ARIGATO', 'BA-SH', 'BALENCIAGA', 'BALLIN-AMSTERDAM', 'BALLY', 'BALMAIN', 'BALR', 'BARGAIN', 'BAUM-UND-PFERDGARTEN', 'BE-EDGY', 'BELIEVE-THAT', 'BELLA-DAHL', 'BELLA-FREUD', 'BIANCO', 'BIBI-LOU', 'BIKKEMBERGS', 'BILLIONAIRE', 'BILLIONAIRE-BOYS-CLUB', 'BIRKENSTOCK', 'BJoRN-BORG', 'BLACK-BANANAS', 'BLACKSTONE', 'BLAUER', 'BLUMARINE', 'BOMBOOGIE', 'BORAGIO', 'BOTTEGA-VENETA', 'BOUTIQUE-MOSCHINO', 'BRONX', 'BTQ24', 'BUDDHA-TO-BUDDHA', 'BURBERRY', 'BUSCEMI', 'BUTCHER-OF-BLUE', 'BY-MALENE-BIRGER', 'BY-RISQUE', 'CALVIN-KLEIN', 'CALVIN-KLEIN-205W39NYC', 'CAMBIO', 'CANADA-GOOSE', 'CANADIAN-CLASSICS', 'CANADIENS', 'CAPSLAB', 'CARHARTT', 'CARLO-COLUCCI', 'CASABLANCA', 'CASADEI', 'CATWALK', 'CATWALK-JUNKIE', 'CAVALLI-CLASS', 'CEASARSS', 'CELESTO', 'CELINE', 'CERO-NINE', 'CHAMPION', 'CHANEL', 'CHIARA-FERRAGNI', 'CHLOe', 'CHRISTIAN-LOUBOUTIN', 'CHURCH-S', 'CIRCLE-OF-TRUST', 'CLAN-DE-BANLIEUE', 'CLARKS', 'CLARKS-ORIGINAL', 'CLIC', 'CLJD', 'CLOSED', 'COACH', 'COCCINELLE', 'COLMAR-ORIGINALS', 'COMME-DES-GARcONS', 'COMMON-PROJECTS', 'CONFIRM', 'CONFLICT', 'CONVERSE', 'COPENHAGEN', 'CORNELIANI', 'CORTICA', 'CP-COMPANY', 'CRUYFF', 'DAILY-PAPER', 'DANIELE-FIESOLI', 'DANCE-SPRING', 'DANTE-6', 'DATE', 'DEAN-RICH', 'DENHAM', 'DESA', 'DEUS', 'DIADORA', 'DIADORA-HERITAGE', 'DIANE-VON-FURSTENBERG', 'DIESEL', 'DIMORAL', 'DIOR', 'DITA', 'DKNY', 'DOLCE-GABBANA', 'DONDUP', 'DR-MARTENS', 'DRIES-VAN-NOTEN', 'DRÔLE-DE-MONSIEUR', 'DRYKORN', 'dsqUARED2', 'DU00', 'EA7', 'ELENIA-LACHI', 'ELISABETTA-FRANCHI', 'ELLESSE', 'ELVINE', 'EMPORIO-ARMANI', 'EQUALITe', 'EQUIPMENT', 'ESSENTIAL', 'ETQ-AMSTERDAM', 'EVISU', 'EXPRESSO', 'FABIANA-FILIPPI', 'FABIENNE-CHAPOT', 'FARLo-PALU', 'FEDERAL-JEANS', 'FENDI', 'FIAMME', 'FIFTH-HOUSE', 'FIGHTR', 'FILA', 'FILIPPA-K', 'FILLING-PIECES', 'FIORUCCI', 'FLORIS-VAN-BOMMEL', 'FOR-ART-S-SAKE', 'FOSSIL', 'FRANCESCO-RUSSO', 'FRANKIE-MORELLO', 'FRED-DE-LA-BRETONIERE', 'FRED-PERRY', 'FREEBIRD', 'FRIDA', 'FURLA', 'FUTURE-ICON', 'G-STAR-RAW', 'GABBA', 'GANNI', 'GARMENT-PROJECT', 'GCDS', 'GENTI', 'GENTILUOMO', 'GESTUZ', 'GHoUD', 'GIACOMO', 'GIANNI-CHIARINI', 'GIANVITO-ROSSI', 'GIGI-VITALE', 'GIORGIO-ARMANI', 'GIPSY', 'GIUSEPPE-ZANOTTI', 'GIVEN', 'GIVENCHY', 'GLAMOROUS', 'GOLDBERGH', 'GOLDEN-GOOSE', 'GOORIN-BROTHERS', 'GOOSECRAFT', 'GREG-NOISE', 'GUCCI', 'GUESS', 'GUESS-BY-MARCIANO', 'GUGLIELMO-ROTTA', 'HAVAIANAS', 'HELMUT-LANG', 'HELVETICA', 'HERMES', 'HERNO', 'HERON-PRESTON', 'HETREGO', 'HI-TEC', 'HIGH', 'HINSON', 'HINSON-STUDIOS', 'HIP', 'HOGAN', 'HUGO', 'HUGO-BOSS', 'HVISK', 'IBANA', 'ICEBERG', 'ICEPLAY', 'IN-GOLD-WE-TRUST', 'IRO', 'ISABEL-MARANT', 'J-BRAND', 'JACKY-LUXURY', 'JACOB-COHEN', 'JANET-JANET', 'JAPAN-TKY', 'JEANROIS', 'JIL-SANDER', 'JIM-RICKEY', 'JIMMY-CHOO', 'JO-GHOST', 'JOHN-RICHMOND', 'JORCUSTOM', 'JORIK', 'JOSEPH', 'JOSH-V', 'JOTT', 'JUST-CAVALLI', 'JUST-JUNKIES', 'KAPPA', 'KARL-LAGERFELD', 'KAT-MACONIE', 'KENDALL-KYLIE', 'KENNEL-SCHMENGER', 'KENT-CURWEN', 'KENZO', 'KINGS-WILL-DREAM', 'KOCCA', 'KRAKATAU', 'KULTIVATE', 'LA-SISTERS', 'LACOSTE', 'LANVIN', 'LEVI-S', 'LEYON', 'LIMITATO', 'LIU-JO', 'LOEWE', 'LOIS', 'LOLA-CRUZ', 'LORENZONI', 'LOUIS-VUITTON', 'LOVE-MOSCHINO', 'LYLE-SCOTT', 'MA-STRUM', 'MAEL-STUDIO', 'MAGNANNI', 'MAISON-KITSUNe', 'MAISON-MARGIELA', 'MAISON-SCOTCH', 'MAJESTIC', 'MALELIONS', 'MALLET', 'MARC-CAIN', 'MARC-JACOBS', 'MARCELO-BURLON', 'MARCH-23', 'MARIA-TAILOR', 'MARNI', 'MARTINE-ROSE', 'MASON-GARMENTS', 'MASON-S', 'MASSIMO-VILLA', 'MAURY', 'MAX-MARA', 'MBYM', 'MCM', 'MCQ-ALEXANDER-MCQUEEN', 'MERCER-AMSTERDAM', 'MESMO-SINCE-DAY-ONE', 'WITH-JEANS', 'MICHAEL-KORS', 'MILLA-AMSTERDAM', 'MINIMUM', 'MISBHV', 'MISS-JUNE', 'MISSONI', 'MIU-MIU', 'MLLNR', 'MM6-MAISON-MARGIELA', 'MODSTRoM', 'MONCLER', 'MONNALISA', 'MOOSE-KNUCKLES', 'MOOST-WANTED', 'MORESCHI', 'MORSE-CODE', 'MOS-MOSH', 'MOSCHINO', 'MOSCOW', 'MOSS-COPENHAGEN', 'MSGM', 'MUSEUM', 'MY-BRAND', 'N21', 'NA-KD', 'NAPAPIJRI', 'NEIL-BARRETT', 'NERO-GIARDINI', 'NEW-AMSTERDAM-SURF-ASSOCIATION', 'NEW-BALANCE', 'NEW-ERA', 'NEWAMS', 'NIK-NIK', 'NIKE', 'NIKKIE', 'NINE-IN-THE-MORNING', 'NINETYFOUR', 'NN07', 'NUBIKK', 'NUDIE-JEANS', 'OAKLEY', 'OFF-THE-PITCH', 'OFF-WHITE', 'oLAF', 'ONCE-WE-WERE-WARRIORS', 'OSC', 'P448', 'PALM-ANGELS', 'PARAJUMPERS', 'PARIS-PUNK', 'PATAGONIA', 'PATRIZIA-PEPE', 'PAUL-SHARK', 'PAUL-SMITH', 'PEAK-PERFORMANCE', 'PEDRO-MIRALLES', 'PENN-INK', 'PEOPLE-OF-SHIBUYA', 'PERTINI', 'PETER-KAISER', 'PEUTEREY', 'PHARMACY-CLUB', 'PHILIPP-PLEIN', 'PHILIPPE-MODEL', 'PHILOSOPHY', 'PHILOU', 'PINKO', 'PLAIN', 'PLEASURES', 'POELMAN', 'PRADA', 'PREMIATA', 'PROENZA-SCHOULER', 'PROFUOMO', 'PRPS', 'PUMA', 'PUREWHITE', 'PYREX', 'QUOTRELL', 'RADICAL', 'RAF-SIMONS', 'RAGYARD', 'RALPH-LAUREN', 'SAVE-VALENTINO', 'REEBOK', 'REHAB', 'REINDERS', 'REPEAT', 'REPLAY', 'REPRESENT', 'REPRIMAND', 'RESET', 'RHUDE', 'RICHESSE', 'RICK-OWENS', 'RINASCIMENTO', 'ROBERT-FRIEDMAN', 'ROBERTO-D-ANGELO', 'ROKA-ORIGINAL', 'ROTTA', 'ROUGH-STUDIOS', 'ROYAL-REPUBLIQ', 'ROYAL-TEMPTATION', 'RRD', 'RTA', 'SACAI', 'SAINT-LAURENT', 'SAMSoE-SAMSoE', 'SANTONI', 'SAUCONY', 'SAVE-THE-DUCK', 'SCOTCH-SODA', 'SECOND-FEMALE', 'SELF-PORTRAIT', 'SENDRA', 'SERGIO-ROSSI', 'SET', 'SHABBIES', 'SHE-IS-US', 'SIKSILK', 'SILVIAN-HEACH', 'SIXTH-JUNE', 'SKECHERS', 'SPLINTER', 'SPRAYGROUND', 'STAND', 'STATEMENTMASK', 'STELLA-MCCARTNEY', 'STEVE-MADDEN', 'STINE-GOYA', 'STOKTON', 'STONE-ISLAND-JUNIOR', 'STUART-WEITZMAN', 'STUDIO-ANNELOES', 'STÜSSY', 'SUMMUM', 'SUNDEK', 'SUPERGA', 'SUPER-TRASH', 'SUSTAIN', 'SVNTY', 'SZIANO', 'TAGLIATORE', 'TANGO', 'TARTINE-ET-CHOCOLAT', 'TED-BAKER', 'THE-GOODPEOPLE', 'THE-NORTH-FACE', 'THOM-BROWNE', 'THROWBACK', 'TIGHA', 'TIMBERLAND', 'TOD-S', 'TOM-FORD', 'TOMMY-HILFIGER', 'TORAL', 'TORY-BURCH', 'TRUSSARDI-JEANS', 'TW-STEEL', 'TWIN-SET', 'TWISTED-BABYDOLL', 'UGG', 'UNDER-ARMOR', 'UNISA', 'UNKNOWN-ARMY', 'VALENTINO', 'VALENTINO-BY-MARIO-VALENTINO', 'VAN-BOMMEL', 'VANS', 'VEJA', 'VERSACE', 'VERSACE-JEANS', 'VERSUS', 'VESPA', 'VETEMENTS', 'VIA-VAI', 'VICTORIA-BECKHAM', 'VINCE', 'VIVIENNE-WESTWOOD', 'VOILE-BLANCHE', 'WANDERLUST', 'WANDLER', 'WHAT-FOR', 'WINKELSTRAAT-NL', 'WOOLRICH', 'WRONG-FRIENDS', 'XPLCT-STUDIOS', 'Y-3', 'YAYA', 'YCLO', 'YEEZLOUISE', 'YEEZY', 'YVES-CARTER', 'ZADIG-ET-VOLTAIRE', 'ZOE-KARSSEN', 'ZUMO'],
    'designer_dutch': ['10-DAYS', '1017-ALYX-9SM', '24UOMO', '304', '7-FOR-ALL-MANKIND', 'A-COLD-WALL', 'APC', 'AAIKO', 'AB-LIFESTYLE', 'ACNE-STUDIOS', 'ADIDAS', 'ADIDAS-BY-RAF-SIMONS', 'ADIDAS-BY-STELLA-MCCARTNEY', 'AH6', 'AIRFORCE', 'AK', 'ALAIA', 'ALBERTA-FERRETTI', 'ALBERTO-BELLINI', 'ALBERTO-GOZZI', 'ALEXANDER-MCQUEEN', 'ALEXANDER-SMITH', 'ALEXANDER-WANG', 'ALEXANDRE-BIRMAN', 'ALEXANDRE-VAUTHIER', 'ALIFE®', 'ALIX', 'ALLDEY', 'ALPHA-INDUSTRIES', 'ALYX', 'AMI-PARIS', 'AMIRI', 'ANDROID', 'ANDROID-HOMME', 'ANINE-BING', 'ANOTHER-WORLD-CLOTHING', 'ANTONY-MORATO', 'AQUAZZURA', 'ARC-TERYX', 'ARKK-COPENHAGEN', 'ARMA-LEDER', 'ARMANI-BABY', 'ARMANI-EXCHANGE', 'ARMANI-JEANS', 'ARMANI-JUNIOR', 'ASH-ITALIA', 'ASICS', 'ASPESI', 'ATLANTIC-STARS', 'ATTILIO-GIUSTI-LEOMBRUNI', 'AUSTRALIAN', 'AVIOR', 'AXEL-ARIGATO', 'BA-SH', 'BALENCIAGA', 'BALLIN-AMSTERDAM', 'BALLY', 'BALMAIN', 'BALR', 'BARGAIN', 'BAUM-UND-PFERDGARTEN', 'BE-EDGY', 'BELIEVE-THAT', 'BELLA-DAHL', 'BELLA-FREUD', 'BIANCO', 'BIBI-LOU', 'BIKKEMBERGS', 'BILLIONAIRE', 'BILLIONAIRE-BOYS-CLUB', 'BIRKENSTOCK', 'BJoRN-BORG', 'BLACK-BANANAS', 'BLACKSTONE', 'BLAUER', 'BLUMARINE', 'BOMBOOGIE', 'BORAGIO', 'BOTTEGA-VENETA', 'BOUTIQUE-MOSCHINO', 'BRONX', 'BTQ24', 'BUDDHA-TO-BUDDHA', 'BURBERRY', 'BUSCEMI', 'BUTCHER-OF-BLUE', 'BY-MALENE-BIRGER', 'BY-RISQUE', 'CALVIN-KLEIN', 'CALVIN-KLEIN-205W39NYC', 'CAMBIO', 'CANADA-GOOSE', 'CANADIAN-CLASSICS', 'CANADIENS', 'CAPSLAB', 'CARHARTT', 'CARLO-COLUCCI', 'CASABLANCA', 'CASADEI', 'CATWALK', 'CATWALK-JUNKIE', 'CAVALLI-CLASS', 'CEASARSS', 'CELESTO', 'CELINE', 'CERO-NINE', 'CHAMPION', 'CHANEL', 'CHIARA-FERRAGNI', 'CHLOe', 'CHRISTIAN-LOUBOUTIN', 'CHURCH-S', 'CIRCLE-OF-TRUST', 'CLAN-DE-BANLIEUE', 'CLARKS', 'CLARKS-ORIGINAL', 'CLIC', 'CLJD', 'CLOSED', 'COACH', 'COCCINELLE', 'COLMAR-ORIGINALS', 'COMME-DES-GARcONS', 'COMMON-PROJECTS', 'CONFIRM', 'CONFLICT', 'CONVERSE', 'COPENHAGEN', 'CORNELIANI', 'CORTICA', 'CP-COMPANY', 'CRUYFF', 'DAILY-PAPER', 'DANIELE-FIESOLI', 'DANCE-SPRING', 'DANTE-6', 'DATE', 'DEAN-RICH', 'DENHAM', 'DESA', 'DEUS', 'DIADORA', 'DIADORA-HERITAGE', 'DIANE-VON-FURSTENBERG', 'DIESEL', 'DIMORAL', 'DIOR', 'DITA', 'DKNY', 'DOLCE-GABBANA', 'DONDUP', 'DR-MARTENS', 'DRIES-VAN-NOTEN', 'DRÔLE-DE-MONSIEUR', 'DRYKORN', 'dsqUARED2', 'DU00', 'EA7', 'ELENIA-LACHI', 'ELISABETTA-FRANCHI', 'ELLESSE', 'ELVINE', 'EMPORIO-ARMANI', 'EQUALITe', 'EQUIPMENT', 'ESSENTIAL', 'ETQ-AMSTERDAM', 'EVISU', 'EXPRESSO', 'FABIANA-FILIPPI', 'FABIENNE-CHAPOT', 'FARLo-PALU', 'FEDERAL-JEANS', 'FENDI', 'FIAMME', 'FIFTH-HOUSE', 'FIGHTR', 'FILA', 'FILIPPA-K', 'FILLING-PIECES', 'FIORUCCI', 'FLORIS-VAN-BOMMEL', 'FOR-ART-S-SAKE', 'FOSSIL', 'FRANCESCO-RUSSO', 'FRANKIE-MORELLO', 'FRED-DE-LA-BRETONIERE', 'FRED-PERRY', 'FREEBIRD', 'FRIDA', 'FURLA', 'FUTURE-ICON', 'G-STAR-RAW', 'GABBA', 'GANNI', 'GARMENT-PROJECT', 'GCDS', 'GENTI', 'GENTILUOMO', 'GESTUZ', 'GHoUD', 'GIACOMO', 'GIANNI-CHIARINI', 'GIANVITO-ROSSI', 'GIGI-VITALE', 'GIORGIO-ARMANI', 'GIPSY', 'GIUSEPPE-ZANOTTI', 'GIVEN', 'GIVENCHY', 'GLAMOROUS', 'GOLDBERGH', 'GOLDEN-GOOSE', 'GOORIN-BROTHERS', 'GOOSECRAFT', 'GREG-NOISE', 'GUCCI', 'GUESS', 'GUESS-BY-MARCIANO', 'GUGLIELMO-ROTTA', 'HAVAIANAS', 'HELMUT-LANG', 'HELVETICA', 'HERMES', 'HERNO', 'HERON-PRESTON', 'HETREGO', 'HI-TEC', 'HIGH', 'HINSON', 'HINSON-STUDIOS', 'HIP', 'HOGAN', 'HUGO', 'HUGO-BOSS', 'HVISK', 'IBANA', 'ICEBERG', 'ICEPLAY', 'IN-GOLD-WE-TRUST', 'IRO', 'ISABEL-MARANT', 'J-BRAND', 'JACKY-LUXURY', 'JACOB-COHEN', 'JANET-JANET', 'JAPAN-TKY', 'JEANROIS', 'JIL-SANDER', 'JIM-RICKEY', 'JIMMY-CHOO', 'JO-GHOST', 'JOHN-RICHMOND', 'JORCUSTOM', 'JORIK', 'JOSEPH', 'JOSH-V', 'JOTT', 'JUST-CAVALLI', 'JUST-JUNKIES', 'KAPPA', 'KARL-LAGERFELD', 'KAT-MACONIE', 'KENDALL-KYLIE', 'KENNEL-SCHMENGER', 'KENT-CURWEN', 'KENZO', 'KINGS-WILL-DREAM', 'KOCCA', 'KRAKATAU', 'KULTIVATE', 'LA-SISTERS', 'LACOSTE', 'LANVIN', 'LEVI-S', 'LEYON', 'LIMITATO', 'LIU-JO', 'LOEWE', 'LOIS', 'LOLA-CRUZ', 'LORENZONI', 'LOUIS-VUITTON', 'LOVE-MOSCHINO', 'LYLE-SCOTT', 'MASTRUM', 'MAEL-STUDIO', 'MAGNANNI', 'MAISON-KITSUNe', 'MAISON-MARGIELA', 'MAISON-SCOTCH', 'MAJESTIC', 'MALELIONS', 'MALLET', 'MARC-CAIN', 'MARC-JACOBS', 'MARCELO-BURLON', 'MARCH-23', 'MARIA-TAILOR', 'MARNI', 'MARTINE-ROSE', 'MASON-GARMENTS', 'MASON-S', 'MASSIMO-VILLA', 'MAURY', 'MAX-MARA', 'MBYM', 'MCM', 'MCQ-ALEXANDER-MCQUEEN', 'MERCER-AMSTERDAM', 'MESMO-SINCE-DAY-ONE', 'WITH-JEANS', 'MICHAEL-KORS', 'MILLA-AMSTERDAM', 'MINIMUM', 'MISBHV', 'MISS-JUNE', 'MISSONI', 'MIU-MIU', 'MLLNR', 'MM6-MAISON-MARGIELA', 'MODSTRoM', 'MONCLER', 'MONNALISA', 'MOOSE-KNUCKLES', 'MOOST-WANTED', 'MORESCHI', 'MORSE-CODE', 'MOS-MOSH', 'MOSCHINO', 'MOSCOW', 'MOSS-COPENHAGEN', 'MSGM', 'MUSEUM', 'MY-BRAND', 'N21', 'NA-KD', 'NAPAPIJRI', 'NEIL-BARRETT', 'NERO-GIARDINI', 'NEW-AMSTERDAM-SURF-ASSOCIATION', 'NEW-BALANCE', 'NEW-ERA', 'NEWAMS', 'NIK-NIK', 'NIKE', 'NIKKIE', 'NINE-IN-THE-MORNING', 'NINETYFOUR', 'NN07', 'NUBIKK', 'NUDIE-JEANS', 'OAKLEY', 'OFF-THE-PITCH', 'OFF-WHITE', 'oLAF', 'ONCE-WE-WERE-WARRIORS', 'OSC', 'P448', 'PALM-ANGELS', 'PARAJUMPERS', 'PARIS-PUNK', 'PATAGONIA', 'PATRIZIA-PEPE', 'PAUL-SHARK', 'PAUL-SMITH', 'PEAK-PERFORMANCE', 'PEDRO-MIRALLES', 'PENN-INK', 'PEOPLE-OF-SHIBUYA', 'PERTINI', 'PETER-KAISER', 'PEUTEREY', 'PHARMACY-CLUB', 'PHILIPP-PLEIN', 'PHILIPPE-MODEL', 'PHILOSOPHY', 'PHILOU', 'PINKO', 'PLAIN', 'PLEASURES', 'POELMAN', 'PRADA', 'PREMIATA', 'PROENZA-SCHOULER', 'PROFUOMO', 'PRPS', 'PUMA', 'PUREWHITE', 'PYREX', 'QUOTRELL', 'RADICAL', 'RAF-SIMONS', 'RAGYARD', 'RALPH-LAUREN', 'SAVE-VALENTINO', 'REEBOK', 'REHAB', 'REINDERS', 'REPEAT', 'REPLAY', 'REPRESENT', 'REPRIMAND', 'RESET', 'RHUDE', 'RICHESSE', 'RICK-OWENS', 'RINASCIMENTO', 'ROBERT-FRIEDMAN', 'ROBERTO-D-ANGELO', 'ROKA-ORIGINAL', 'ROTTA', 'ROUGH-STUDIOS', 'ROYAL-REPUBLIQ', 'ROYAL-TEMPTATION', 'RRD', 'RTA', 'SACAI', 'SAINT-LAURENT', 'SAMSoE-SAMSoE', 'SANTONI', 'SAUCONY', 'SAVE-THE-DUCK', 'SCOTCH-SODA', 'SECOND-FEMALE', 'SELF-PORTRAIT', 'SENDRA', 'SERGIO-ROSSI', 'SET', 'SHABBIES', 'SHE-IS-US', 'SIKSILK', 'SILVIAN-HEACH', 'SIXTH-JUNE', 'SKECHERS', 'SPLINTER', 'SPRAYGROUND', 'STAND', 'STATEMENTMASK', 'STELLA-MCCARTNEY', 'STEVE-MADDEN', 'STINE-GOYA', 'STOKTON', 'STONE-ISLAND-JUNIOR', 'STUART-WEITZMAN', 'STUDIO-ANNELOES', 'STÜSSY', 'SUMMUM', 'SUNDEK', 'SUPERGA', 'SUPER-TRASH', 'SUSTAIN', 'SVNTY', 'SZIANO', 'TAGLIATORE', 'TANGO', 'TARTINE-ET-CHOCOLAT', 'TED-BAKER', 'THE-GOODPEOPLE', 'THE-NORTH-FACE', 'THOM-BROWNE', 'THROWBACK', 'TIGHA', 'TIMBERLAND', 'TOD-S', 'TOM-FORD', 'TOMMY-HILFIGER', 'TORAL', 'TORY-BURCH', 'TRUSSARDI-JEANS', 'TW-STEEL', 'TWIN-SET', 'TWISTED-BABYDOLL', 'UGG', 'UNDER-ARMOR', 'UNISA', 'UNKNOWN-ARMY', 'VALENTINO', 'VALENTINO-BY-MARIO-VALENTINO', 'VAN-BOMMEL', 'VANS', 'VEJA', 'VERSACE', 'VERSACE-JEANS', 'VERSUS', 'VESPA', 'VETEMENTS', 'VIA-VAI', 'VICTORIA-BECKHAM', 'VINCE', 'VIVIENNE-WESTWOOD', 'VOILE-BLANCHE', 'WANDERLUST', 'WANDLER', 'WHAT-FOR', 'WINKELSTRAAT-NL', 'WOOLRICH', 'WRONG-FRIENDS', 'XPLCT-STUDIOS', 'Y-3', 'YAYA', 'YCLO', 'YEEZLOUISE', 'YEEZY', 'YVES-CARTER', 'ZADIG-ET-VOLTAIRE', 'ZOE-KARSSEN', 'ZUMO'],
    'designer_luxe': ['ALEXANDER-MCQUEEN', 'ALEXANDER-WANG', 'ALYX', 'AMIRI', 'AQUAZZURA', 'BALENCIAGA', 'BALMAIN', 'BURBERRY', 'CALVIN-KLEIN-205W39NYC', 'CANADA-GOOSE', 'CASADEI', 'CHLOe', 'COACH', 'DIOR', 'DOLCE-GABBANA', 'dsqUARED2', 'FENDI', 'GIUSEPPE-ZANOTTI', 'GIVENCHY', 'GOLDEN-GOOSE', 'GUCCI', 'HERON-PRESTON', 'ISABEL-MARANT', 'JIMMY-CHOO', 'KENZO', 'LANVIN', 'LOEWE', 'MAISON-MARGIELA', 'MARCELO-BURLON', 'MISSONI', 'MIU-MIU', 'MONCLER', 'MOOSE-KNUCKLES', 'MOSCHINO', 'MSGM', 'NEIL-BARRETT', 'OFF-WHITE', 'PALM-ANGELS', 'PARAJUMPERS', 'PHILIPP-PLEIN', 'PHILIPPE-MODEL', 'PRADA', 'SACAI', 'SAINT-LAURENT', 'STELLA-MCCARTNEY', 'STUART-WEITZMAN', 'TOM-FORD', 'VALENTINO', 'VERSACE', 'VETEMENTS', 'WOOLRICH', 'Y-3'],
    'designer_premium': ['10-DAYS', '1017-ALYX-9SM', '24UOMO', '304', '7-FOR-ALL-MANKIND', 'A-COLD-WALL', 'APC', 'AAIKO', 'AB-LIFESTYLE', 'ACNE-STUDIOS', 'ADIDAS', 'ADIDAS-BY-RAF-SIMONS', 'ADIDAS-BY-STELLA-MCCARTNEY', 'AH6', 'AIRFORCE', 'AK', 'ALAIA', 'ALBERTA-FERRETTI', 'ALBERTO-BELLINI', 'ALBERTO-GOZZI', 'ALEXANDER-MCQUEEN', 'ALEXANDER-SMITH', 'ALEXANDER-WANG', 'ALEXANDRE-BIRMAN', 'ALEXANDRE-VAUTHIER', 'ALIFE®', 'ALIX', 'ALLDEY', 'ALPHA-INDUSTRIES', 'ALYX', 'AMI-PARIS', 'AMIRI', 'ANDROID', 'ANDROID-HOMME', 'ANINE-BING', 'ANOTHER-WORLD-CLOTHING', 'ANTONY-MORATO', 'AQUAZZURA', 'ARC-TERYX', 'ARKK-COPENHAGEN', 'ARMA-LEDER', 'ARMANI-BABY', 'ARMANI-EXCHANGE', 'ARMANI-JEANS', 'ARMANI-JUNIOR', 'ASH-ITALIA', 'ASICS', 'ASPESI', 'ATLANTIC-STARS', 'ATTILIO-GIUSTI-LEOMBRUNI', 'AUSTRALIAN', 'AVIOR', 'AXEL-ARIGATO', 'BA-SH', 'BALENCIAGA', 'BALLIN-AMSTERDAM', 'BALLY', 'BALMAIN', 'BALR', 'BARGAIN', 'BAUM-UND-PFERDGARTEN', 'BE-EDGY', 'BELIEVE-THAT', 'BELLA-DAHL', 'BELLA-FREUD', 'BIANCO', 'BIBI-LOU', 'BIKKEMBERGS', 'BILLIONAIRE', 'BILLIONAIRE-BOYS-CLUB', 'BIRKENSTOCK', 'BJoRN-BORG', 'BLACK-BANANAS', 'BLACKSTONE', 'BLAUER', 'BLUMARINE', 'BOMBOOGIE', 'BORAGIO', 'BOTTEGA-VENETA', 'BOUTIQUE-MOSCHINO', 'BRONX', 'BTQ24', 'BUDDHA-TO-BUDDHA', 'BURBERRY', 'BUSCEMI', 'BUTCHER-OF-BLUE', 'BY-MALENE-BIRGER', 'BY-RISQUE', 'CALVIN-KLEIN', 'CALVIN-KLEIN-205W39NYC', 'CAMBIO', 'CANADA-GOOSE', 'CANADIAN-CLASSICS', 'CANADIENS', 'CAPSLAB', 'CARHARTT', 'CARLO-COLUCCI', 'CASABLANCA', 'CASADEI', 'CATWALK', 'CATWALK-JUNKIE', 'CAVALLI-CLASS', 'CEASARSS', 'CELESTO', 'CELINE', 'CERO-NINE', 'CHAMPION', 'CHANEL', 'CHIARA-FERRAGNI', 'CHLOe', 'CHRISTIAN-LOUBOUTIN', 'CHURCH-S', 'CIRCLE-OF-TRUST', 'CLAN-DE-BANLIEUE', 'CLARKS', 'CLARKS-ORIGINAL', 'CLIC', 'CLJD', 'CLOSED', 'COACH', 'COCCINELLE', 'COLMAR-ORIGINALS', 'COMME-DES-GARcONS', 'COMMON-PROJECTS', 'CONFIRM', 'CONFLICT', 'CONVERSE', 'COPENHAGEN', 'CORNELIANI', 'CORTICA', 'CP-COMPANY', 'CRUYFF', 'DAILY-PAPER', 'DANIELE-FIESOLI', 'DANCE-SPRING', 'DANTE-6', 'DATE', 'DEAN-RICH', 'DENHAM', 'DESA', 'DEUS', 'DIADORA', 'DIADORA-HERITAGE', 'DIANE-VON-FURSTENBERG', 'DIESEL', 'DIMORAL', 'DIOR', 'DITA', 'DKNY', 'DOLCE-GABBANA', 'DONDUP', 'DR-MARTENS', 'DRIES-VAN-NOTEN', 'DRÔLE-DE-MONSIEUR', 'DRYKORN', 'dsqUARED2', 'DU00', 'EA7', 'ELENIA-LACHI', 'ELISABETTA-FRANCHI', 'ELLESSE', 'ELVINE', 'EMPORIO-ARMANI', 'EQUALITe', 'EQUIPMENT', 'ESSENTIAL', 'ETQ-AMSTERDAM', 'EVISU', 'EXPRESSO', 'FABIANA-FILIPPI', 'FABIENNE-CHAPOT', 'FARLo-PALU', 'FEDERAL-JEANS', 'FENDI', 'FIAMME', 'FIFTH-HOUSE', 'FIGHTR', 'FILA', 'FILIPPA-K', 'FILLING-PIECES', 'FIORUCCI', 'FLORIS-VAN-BOMMEL', 'FOR-ART-S-SAKE', 'FOSSIL', 'FRANCESCO-RUSSO', 'FRANKIE-MORELLO', 'FRED-DE-LA-BRETONIERE', 'FRED-PERRY', 'FREEBIRD', 'FRIDA', 'FURLA', 'FUTURE-ICON', 'G-STAR-RAW', 'GABBA', 'GANNI', 'GARMENT-PROJECT', 'GCDS', 'GENTI', 'GENTILUOMO', 'GESTUZ', 'GHoUD', 'GIACOMO', 'GIANNI-CHIARINI', 'GIANVITO-ROSSI', 'GIGI-VITALE', 'GIORGIO-ARMANI', 'GIPSY', 'GIUSEPPE-ZANOTTI', 'GIVEN', 'GIVENCHY', 'GLAMOROUS', 'GOLDBERGH', 'GOLDEN-GOOSE', 'GOORIN-BROTHERS', 'GOOSECRAFT', 'GREG-NOISE', 'GUCCI', 'GUESS', 'GUESS-BY-MARCIANO', 'GUGLIELMO-ROTTA', 'HAVAIANAS', 'HELMUT-LANG', 'HELVETICA', 'HERMES', 'HERNO', 'HERON-PRESTON', 'HETREGO', 'HI-TEC', 'HIGH', 'HINSON', 'HINSON-STUDIOS', 'HIP', 'HOGAN', 'HUGO', 'HUGO-BOSS', 'HVISK', 'IBANA', 'ICEBERG', 'ICEPLAY', 'IN-GOLD-WE-TRUST', 'IRO', 'ISABEL-MARANT', 'J-BRAND', 'JACKY-LUXURY', 'JACOB-COHEN', 'JANET-JANET', 'JAPAN-TKY', 'JEANROIS', 'JIL-SANDER', 'JIM-RICKEY', 'JIMMY-CHOO', 'JO-GHOST', 'JOHN-RICHMOND', 'JORCUSTOM', 'JORIK', 'JOSEPH', 'JOSH-V', 'JOTT', 'JUST-CAVALLI', 'JUST-JUNKIES', 'KAPPA', 'KARL-LAGERFELD', 'KAT-MACONIE', 'KENDALL-KYLIE', 'KENNEL-SCHMENGER', 'KENT-CURWEN', 'KENZO', 'KINGS-WILL-DREAM', 'KOCCA', 'KRAKATAU', 'KULTIVATE', 'LA-SISTERS', 'LACOSTE', 'LANVIN', 'LEVI-S', 'LEYON', 'LIMITATO', 'LIU-JO', 'LOEWE', 'LOIS', 'LOLA-CRUZ', 'LORENZONI', 'LOUIS-VUITTON', 'LOVE-MOSCHINO', 'LYLE-SCOTT', 'MA-STRUM', 'MAEL-STUDIO', 'MAGNANNI', 'MAISON-KITSUNe', 'MAISON-MARGIELA', 'MAISON-SCOTCH', 'MAJESTIC', 'MALELIONS', 'MALLET', 'MARC-CAIN', 'MARC-JACOBS', 'MARCELO-BURLON', 'MARCH-23', 'MARIA-TAILOR', 'MARNI', 'MARTINE-ROSE', 'MASON-GARMENTS', 'MASON-S', 'MASSIMO-VILLA', 'MAURY', 'MAX-MARA', 'MBYM', 'MCM', 'MCQ-ALEXANDER-MCQUEEN', 'MERCER-AMSTERDAM', 'MESMO-SINCE-DAY-ONE', 'WITH-JEANS', 'MICHAEL-KORS', 'MILLA-AMSTERDAM', 'MINIMUM', 'MISBHV', 'MISS-JUNE', 'MISSONI', 'MIU-MIU', 'MLLNR', 'MM6-MAISON-MARGIELA', 'MODSTRoM', 'MONCLER', 'MONNALISA', 'MOOSE-KNUCKLES', 'MOOST-WANTED', 'MORESCHI', 'MORSE-CODE', 'MOS-MOSH', 'MOSCHINO', 'MOSCOW', 'MOSS-COPENHAGEN', 'MSGM', 'MUSEUM', 'MY-BRAND', 'N21', 'NA-KD', 'NAPAPIJRI', 'NEIL-BARRETT', 'NERO-GIARDINI', 'NEW-AMSTERDAM-SURF-ASSOCIATION', 'NEW-BALANCE', 'NEW-ERA', 'NEWAMS', 'NIK-NIK', 'NIKE', 'NIKKIE', 'NINE-IN-THE-MORNING', 'NINETYFOUR', 'NN07', 'NUBIKK', 'NUDIE-JEANS', 'OAKLEY', 'OFF-THE-PITCH', 'OFF-WHITE', 'oLAF', 'ONCE-WE-WERE-WARRIORS', 'OSC', 'P448', 'PALM-ANGELS', 'PARAJUMPERS', 'PARIS-PUNK', 'PATAGONIA', 'PATRIZIA-PEPE', 'PAUL-SHARK', 'PAUL-SMITH', 'PEAK-PERFORMANCE', 'PEDRO-MIRALLES', 'PENN-INK', 'PEOPLE-OF-SHIBUYA', 'PERTINI', 'PETER-KAISER', 'PEUTEREY', 'PHARMACY-CLUB', 'PHILIPP-PLEIN', 'PHILIPPE-MODEL', 'PHILOSOPHY', 'PHILOU', 'PINKO', 'PLAIN', 'PLEASURES', 'POELMAN', 'PRADA', 'PREMIATA', 'PROENZA-SCHOULER', 'PROFUOMO', 'PRPS', 'PUMA', 'PUREWHITE', 'PYREX', 'QUOTRELL', 'RADICAL', 'RAF-SIMONS', 'RAGYARD', 'RALPH-LAUREN', 'SAVE-VALENTINO', 'REEBOK', 'REHAB', 'REINDERS', 'REPEAT', 'REPLAY', 'REPRESENT', 'REPRIMAND', 'RESET', 'RHUDE', 'RICHESSE', 'RICK-OWENS', 'RINASCIMENTO', 'ROBERT-FRIEDMAN', 'ROBERTO-D-ANGELO', 'ROKA-ORIGINAL', 'ROTTA', 'ROUGH-STUDIOS', 'ROYAL-REPUBLIQ', 'ROYAL-TEMPTATION', 'RRD', 'RTA', 'SACAI', 'SAINT-LAURENT', 'SAMSoE-SAMSoE', 'SANTONI', 'SAUCONY', 'SAVE-THE-DUCK', 'SCOTCH-SODA', 'SECOND-FEMALE', 'SELF-PORTRAIT', 'SENDRA', 'SERGIO-ROSSI', 'SET', 'SHABBIES', 'SHE-IS-US', 'SIKSILK', 'SILVIAN-HEACH', 'SIXTH-JUNE', 'SKECHERS', 'SPLINTER', 'SPRAYGROUND', 'STAND', 'STATEMENTMASK', 'STELLA-MCCARTNEY', 'STEVE-MADDEN', 'STINE-GOYA', 'STOKTON', 'STONE-ISLAND-JUNIOR', 'STUART-WEITZMAN', 'STUDIO-ANNELOES', 'STÜSSY', 'SUMMUM', 'SUNDEK', 'SUPERGA', 'SUPER-TRASH', 'SUSTAIN', 'SVNTY', 'SZIANO', 'TAGLIATORE', 'TANGO', 'TARTINE-ET-CHOCOLAT', 'TED-BAKER', 'THE-GOODPEOPLE', 'THE-NORTH-FACE', 'THOM-BROWNE', 'THROWBACK', 'TIGHA', 'TIMBERLAND', 'TOD-S', 'TOM-FORD', 'TOMMY-HILFIGER', 'TORAL', 'TORY-BURCH', 'TRUSSARDI-JEANS', 'TW-STEEL', 'TWIN-SET', 'TWISTED-BABYDOLL', 'UGG', 'UNDER-ARMOR', 'UNISA', 'UNKNOWN-ARMY', 'VALENTINO', 'VALENTINO-BY-MARIO-VALENTINO', 'VAN-BOMMEL', 'VANS', 'VEJA', 'VERSACE', 'VERSACE-JEANS', 'VERSUS', 'VESPA', 'VETEMENTS', 'VIA-VAI', 'VICTORIA-BECKHAM', 'VINCE', 'VIVIENNE-WESTWOOD', 'VOILE-BLANCHE', 'WANDERLUST', 'WANDLER', 'WHAT-FOR', 'WINKELSTRAAT-NL', 'WOOLRICH', 'WRONG-FRIENDS', 'XPLCT-STUDIOS', 'Y-3', 'YAYA', 'YCLO', 'YEEZLOUISE', 'YEEZY', 'YVES-CARTER', 'ZADIG-ET-VOLTAIRE', 'ZOE-KARSSEN', 'ZUMO']}
